import Head from "next/head";
import AppLayout from "../componentes/AppLayout";
import Button from "../componentes/Button";
import { colors } from "../styles/theme";

export default function Home() {
	return (
		<>
			<Head>
				<title>Next Js App </title>
				<meta
					name='description'
					content='Generated by create next app'
				/>
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<AppLayout>
				<section>
					<img src='/vercel.svg' alt='logo app' />
					<h1>Devter</h1>
					<h2> Talk about development with developers 😎</h2>
					<Button>Login with GitHub</Button>
				</section>
			</AppLayout>

			<style jsx>
				{`
					section {
						width: 100%;
						height:100%;
						display : flex;
						flex-direction : column;
						justify-content : center;
						align-items : center;
					}

					img {
						width: 120px;
					}
					h1 {
						color : ${colors.primary}
						font-weight: 800;
					}

					h2 {
						font-size: 16px;
						width:190px;
						text-align:center;
					}
				`}
			</style>
		</>
	);
}
